### ISSUE TITLE
CacheClient.RemoveAsync 无效，执行后，再执行CacheClient.GetAsync依然能获取数据

### ISSUE THREAD

**Issue by xj728** [WeihanLi/WeihanLi.Redis#48]
CacheClient.RemoveAsync 无效，执行后，再执行CacheClient.GetAsync依然能获取数据，
当然Key不变

**Comment by xj728** [comment]
现在用CacheClient.Expire("key",TimeSpan.FromMilliseconds(1) 
来代替删除，没有问题

**Comment by xj728** [comment]
1.5.6.10版本解决了。但是最新版本，删除又报错了。ERR unknown command 'UNLINK'

**Comment by WeihanLi** [comment]
应该不会吧，我看后面的没有再改过这里了，我本地测试也没问题的，你方便给我提供一个小 demo 吗 @xj728

**Comment by xj728** [comment]
2019-12-04 15:16:19.993 +08:00 [Error] ERR unknown command 'UNLINK'
2019-12-04 15:21:09.796 +08:00 [Error] ERR unknown command 'UNLINK'
2019-12-04 15:24:29.379 +08:00 [Error] ERR unknown command 'UNLINK'

换成1.5.6.10这个版本就没问题了。用的是阿里云得redis
给不了demo，在项目中一直用呢

**Comment by WeihanLi** [comment]
感觉像是阿里云 redis 的问题，我是用的本地装的 redis，我再试试

**Comment by WeihanLi** [comment]
@xj728 你在用的阿里云的 redis 是哪一个版本？

redis 从 4.0.0 开始支持 `UNLINK`，如果 redis-server 版本高于 4.0 版本就会使用 `UNLINK` 来代替 `DEL` 来删除 key，看上面的错应该是使用了 `UNLINK` ，但是阿里云redis 不支持

**Comment by WeihanLi** [comment]
@xj728 你好，刚发布了一个 1.5.8.2 版本，你可以通过 `DefaultVersion` 来配置 redis sever 的版本，根据上面的错误，建议使用 3.0.0 版本，配置示例如下：

``` csharp
services.AddRedisConfig(config =>
{
    config.RedisServers = new[]
    {
        new RedisServerConfiguration("127.0.0.1", 16379),
    };
    config.CachePrefix = "WeihanLi.Redis.UnitTest";
    config.ClientName = "WeihanLi.Redis.UnitTest";

    // config.EnableCompress = false;
    config.DefaultDatabase = 0;
    // set RedisServer version
    config.DefaultVersion = new Version(3, 0, 0);
});
```

**Comment by xj728** [comment]
升级到1.5.8.2，加了config.DefaultVersion = new Version(3, 0, 0);之后，阿里云redis不能用了

**Comment by WeihanLi** [comment]
😕 有什么具体的信息吗，你们用的阿里云 redis 的哪个版本？
